version: "3.4"

services:
  whisper-asr:
    image: whisper-asr
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
      - SSL_DOMAIN_NAME=${SSL_DOMAIN_NAME}
      - SSL_EMAIL=${SSL_EMAIL}
      - ASR_MODEL=base
      - OPENAI_WHISPER_API_KEY=${OPENAI_WHISPER_API_KEY}
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80" # certbot
    volumes:
      - ./app:/app/whisper-websocket-streamer
      - /home/stever/projects/cache/whisper:/root/.cache/whisper
      - /home/stever/projects/cache/letsencrypt:/etc/letsencrypt/
    entrypoint:  /app/whisper-websocket-streamer/generate_ssl.sh
    command: /app/.venv/bin/python -m gunicorn --bind 0.0.0.0:443  --workers 1 --reload --timeout 0 --keyfile /etc/letsencrypt/live/${SSL_DOMAIN_NAME}/privkey.pem --certfile /etc/letsencrypt/live/${SSL_DOMAIN_NAME}/cert.pem app.webservice:app -k uvicorn.workers.UvicornWorker
